name: Entrar no Site com Chrome

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  acessar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl gnupg libu2f-udev xvfb

          # Instalar Google Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependências Python
        run: pip install selenium chromedriver-autoinstaller

      - name: Executar script com Chrome headless
        run: xvfb-run python entrar_no_site.py
