name: Entrar no Site

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos (UTC)
  workflow_dispatch:

jobs:
  acessar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl gnupg xvfb

          # Baixa e instala o Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || true
          sudo apt-get -f install -y

          # Descobre a versão principal do Chrome
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.' | head -1 | tr -d '.')
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Instalar dependências Python
        run: pip install selenium

      - name: Rodar o script Python com Xvfb (modo headless compatível com CI)
        run: |
          sudo apt-get install -y xvfb
          xvfb-run python entrar_no_site.py
