name: Entrar no Site

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  acessar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Chrome e ChromeDriver (versão 124)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl gnupg libu2f-udev xvfb

          # Instala o Chrome 124
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_124.0.6367.119-1_amd64.deb
          sudo dpkg -i google-chrome-stable_124.0.6367.119-1_amd64.deb || true
          sudo apt-get -f install -y

          # Instala o ChromeDriver compatível
          wget https://chromedriver.storage.googleapis.com/124.0.6367.119/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Instalar dependências Python
        run: pip install selenium

      - name: Rodar o script Python
        run: xvfb-run python entrar_no_site.py
