name: Entrar no Site com Edge

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  acessar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Microsoft Edge e msedgedriver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

          # Instala o driver correspondente
          EDGE_VERSION=$(microsoft-edge-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          EDGE_MAJOR=$(echo $EDGE_VERSION | cut -d '.' -f 1)
          DRIVER_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE_$EDGE_MAJOR)
          wget https://msedgedriver.azureedge.net/${DRIVER_VERSION}/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/bin/msedgedriver
          sudo chmod +x /usr/bin/msedgedriver

      - name: Instalar dependências Python
        run: pip install selenium

      - name: Rodar script Python com Edge
        run: xvfb-run python entrar_no_site.py
